"""
report_generator.py

Генерирует HTML-отчёт из распарсенных данных Catalyst 2960.
"""

import json
import os
from datetime import datetime

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Network Report — {hostname}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            max-width: 1100px;
            margin: 40px auto;
            padding: 20px;
            background: #f5f5f7;
            color: #1d1d1f;
        }}
        h1 {{
            color: #0071e3;
            border-bottom: 2px solid #0071e3;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #1d1d1f;
            margin-top: 40px;
        }}
        .meta {{
            color: #6e6e73;
            font-size: 14px;
            margin-bottom: 20px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
            margin-bottom: 30px;
        }}
        th {{
            background: #0071e3;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }}
        td {{
            padding: 10px 12px;
            border-bottom: 1px solid #e5e5e7;
        }}
        tr:last-child td {{
            border-bottom: none;
        }}
        tr:hover {{
            background: #f0f7ff;
        }}
        .status-up {{
            color: #34c759;
            font-weight: 600;
        }}
        .status-down {{
            color: #ff3b30;
            font-weight: 600;
        }}
        .footer {{
            text-align: center;
            color: #6e6e73;
            font-size: 12px;
            margin-top: 40px;
        }}
    </style>
</head>
<body>
    <h1>🔍 Network Report — {hostname}</h1>
    <div class="meta">
        Собрано: {collected_at}<br>
        Сгенерировано: {generated_at}
    </div>

    <h2>📋 VLANs ({vlan_count})</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Status</th>
            <th>Ports</th>
        </tr>
        {vlan_rows}
    </table>

    <h2>🔌 Interfaces ({iface_count})</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>IP Address</th>
            <th>Status</th>
            <th>Protocol</th>
        </tr>
        {iface_rows}
    </table>

    <h2>🔗 Ports ({port_count})</h2>
    <table>
        <tr>
            <th>Port</th>
            <th>Status</th>
            <th>VLAN</th>
            <th>Duplex</th>
            <th>Speed</th>
        </tr>
        {port_rows}
    </table>

    <div class="footer">
        Generated by report_generator.py
    </div>
</body>
</html>
"""


def load_parsed(filename="output/parsed.json"):
    """Загружает распарсенные данные."""
    with open(filename, "r", encoding="utf-8") as f:
        return json.load(f)


def build_vlan_rows(vlans):
    """Строит HTML-строки для таблицы VLAN."""
    rows = []
    for vlan in vlans:
        ports = ", ".join(vlan["ports"]) if vlan["ports"] else "—"
        rows.append(
            f"<tr>"
            f"<td>{vlan['id']}</td>"
            f"<td>{vlan['name']}</td>"
            f"<td>{vlan['status']}</td>"
            f"<td>{ports}</td>"
            f"</tr>"
        )
    return "\n        ".join(rows)


def build_iface_rows(interfaces):
    """Строит HTML-строки для таблицы интерфейсов."""
    rows = []
    for iface in interfaces:
        status_class = "status-up" if iface["status"] == "up" else "status-down"
        rows.append(
            f"<tr>"
            f"<td>{iface['name']}</td>"
            f"<td>{iface['ip']}</td>"
            f"<td class='{status_class}'>{iface['status']}</td>"
            f"<td>{iface['protocol']}</td>"
            f"</tr>"
        )
    return "\n        ".join(rows)


def build_port_rows(ports):
    """Строит HTML-строки для таблицы портов."""
    rows = []
    for port in ports:
        rows.append(
            f"<tr>"
            f"<td>{port['port']}</td>"
            f"<td>{port['status']}</td>"
            f"<td>{port['vlan']}</td>"
            f"<td>{port.get('duplex', '—')}</td>"
            f"<td>{port.get('speed', '—')}</td>"
            f"</tr>"
        )
    return "\n        ".join(rows)


def generate_report(data, filename="output/report.html"):
    """Генерирует HTML-отчёт."""
    html = HTML_TEMPLATE.format(
        hostname=data["hostname"],
        collected_at=data["collected_at"],
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        vlan_count=len(data["vlans"]),
        iface_count=len(data["interfaces"]),
        port_count=len(data["ports"]),
        vlan_rows=build_vlan_rows(data["vlans"]),
        iface_rows=build_iface_rows(data["interfaces"]),
        port_rows=build_port_rows(data["ports"]),
    )

    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"💾 Отчёт сохранён в {filename}")


if __name__ == "__main__":
    print("📄 Генерация HTML-отчёта...")
    data = load_parsed()
    generate_report(data)
    print("✅ Готово")
    print(f"📂 Открой в браузере: file://{os.path.abspath('output/report.html')}")